/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TWOG (https://sketchfab.com/TWOG)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-snow-tree-b6555946289f4fc2be92d255daf20518
Title: Low poly snow tree
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import model from '/tree/scene.gltf?url'


export default function Tree(props) {
    const { nodes, materials } = useGLTF(model);
    return (
        <group {...props} dispose={null}>
            <group position={[0, 1.077, 0]} rotation={[0, 0, 0.283]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials['Material.003']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials['Material.002']}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                position={[0, 1.011, 0]}
                scale={[0.231, 1, 0.231]}
                material={materials['Material.001']}
            />
        </group>
    );
}

useGLTF.preload(model);
